FROM maven:3-openjdk-17-slim

RUN useradd -m lunch-buddy
VOLUME ["/user/app"]
WORKDIR /usr/app/
RUN chown lunch-buddy:lunch-buddy /usr/app/
USER lunch-buddy

COPY --chown=lunch-buddy pom.xml ./
RUN mvn dependency:go-offline

ENTRYPOINT ["mvn", "spring-boot:run", \
"-Dspring-boot.run.arguments=--spring.profiles.active=dev", \
"-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
